//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	NEW        OrderStatus = "NEW"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
)

// Balance defines model for Balance.
type Balance struct {
	Current   float32 `json:"current"`
	Withdrawn float32 `json:"withdrawn"`
}

// Order defines model for Order.
type Order struct {
	Accrual    *int        `json:"accrual,omitempty"`
	Number     string      `json:"number"`
	Status     OrderStatus `json:"status"`
	UploadedAt time.Time   `json:"uploaded_at"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       string    `json:"order"`
	ProcessedAt time.Time `json:"processed_at"`
	Sum         float32   `json:"sum"`
}

// PostUserBalanceJSONBody defines parameters for PostUserBalance.
type PostUserBalanceJSONBody struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// PostUserLoginJSONBody defines parameters for PostUserLogin.
type PostUserLoginJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// PostUserOrdersTextBody defines parameters for PostUserOrders.
type PostUserOrdersTextBody = string

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// PostUserBalanceJSONRequestBody defines body for PostUserBalance for application/json ContentType.
type PostUserBalanceJSONRequestBody PostUserBalanceJSONBody

// PostUserLoginJSONRequestBody defines body for PostUserLogin for application/json ContentType.
type PostUserLoginJSONRequestBody PostUserLoginJSONBody

// PostUserOrdersTextRequestBody defines body for PostUserOrders for text/plain ContentType.
type PostUserOrdersTextRequestBody = PostUserOrdersTextBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current balance
	// (GET /user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Request withdrawal
	// (POST /user/balance)
	PostUserBalance(w http.ResponseWriter, r *http.Request)
	// Authenticate an existing user
	// (POST /user/login)
	PostUserLogin(w http.ResponseWriter, r *http.Request)
	// Get list of submitted orders
	// (GET /user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Submit order number for processing
	// (POST /user/orders)
	PostUserOrders(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /user/register)
	PostUserRegister(w http.ResponseWriter, r *http.Request)
	// Get withdrawal history
	// (GET /user/withdrawals)
	GetUserWithdrawals(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserBalance operation middleware
func (siw *ServerInterfaceWrapper) PostUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUserLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserOrders operation middleware
func (siw *ServerInterfaceWrapper) PostUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserWithdrawals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/user/balance", wrapper.GetUserBalance)
	m.HandleFunc("POST "+options.BaseURL+"/user/balance", wrapper.PostUserBalance)
	m.HandleFunc("POST "+options.BaseURL+"/user/login", wrapper.PostUserLogin)
	m.HandleFunc("GET "+options.BaseURL+"/user/orders", wrapper.GetUserOrders)
	m.HandleFunc("POST "+options.BaseURL+"/user/orders", wrapper.PostUserOrders)
	m.HandleFunc("POST "+options.BaseURL+"/user/register", wrapper.PostUserRegister)
	m.HandleFunc("GET "+options.BaseURL+"/user/withdrawals", wrapper.GetUserWithdrawals)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY33PTvBL9VzS6vJE2jpsQaoaHAr3c3Om0HVJuH4DLKNY6FtiSkdZN/TH937+R7PhH",
	"4tBfwPDwvaW1tNo9e/bo2N9pqNJMSZBoaPCdmjCGlLmfr1jCZAj2Z6ZVBhoFuAdhrjVItD/hmqVZAjSY",
	"eN7+ZEAjpVOGNKBRohjSAcUiAxpQmacL0PRmQFcCY67ZSna2j/3b994MqIZvudDAafChzqId8lO9SS2+",
	"QIj2wDPNQW8XwcJQ5yzZLKIOICTCsky5SqC9kh760+eH/sF46jWJGtRCLu0OgwxzdwzIPLXZnh5f0gE9",
	"f3f2+ng+n52+pQM6O/3f0cnsTfPv4ze2gOaM5t89R+RZohgH/pl1G0F9z/f2Rv7eyLsYTYLRJBhPnnoH",
	"gWcTrSHmDGEPRQrboTdgroqva+qe3Af4ZdWOEtwu6mrdjFa+B9Op70+e+eO+MjOtQjDmB3V6hxejZ4F3",
	"GEym96pzQI1tzWb778nCsqAy1ka229jYMyHMtcBibuesxGQBTIM+yjFu/vr3Oov/Xl7Y6G41DaqnTVYx",
	"YkZvbGAhI2X3o0AHz1uVxaBTppG8O55fkKPzGR3QK9BGKEkDOtr39j2LgspAskzQgB64fw1oxjB2mQ1z",
	"A3q4aHRgCa4JHEyoRYZlpHeAWsAVGIIxkGosSaIKlmBBMiUkGlIFIUxyggpZQuqpXS+JlHYRWI4xSBQh",
	"Q+DEprBPXZqa2RNn3FYH+N6AXkuU7YnJlDQlor7nOZ1SEiudYlmW2IBCyeEXo2QjdfbXEw0RDei/ho0W",
	"DishHK6PcCB3C68eEQu9bZdQkpg8tAyI8iQpiK6Q4RbnsTfaxu693K7WLp6UFXQXzySCliwhBvQVaAJa",
	"K91hFQ0+dPn04dPNJ0fOlOmixK3u0LqvdsqU6W3stxwMGsLqZrGEqGizt6hWTHO7zGQQikgAJ24utvt2",
	"rsxW49whrxQv7tCzalZdl69YIngjNlW21ZMcWnLT1Rg39tPJyHW0IcEjhWpTTKaT0aPEpEc9yuXbPO92",
	"rUGEVNiSWpY69Lw3Kcee30dKk0eRCIWlVJRLbtxSv3epa1nJDdJYgl9F9ooRLfK6/aWqJWopHKX6uX/U",
	"QsAQJglcC4NCLh0aLqQTq0yrK8GBExfPyVvGjFkpzXez/8Sd/Wju9zG+Kot+UbHkCpyal+lYtkKoAUf+",
	"Af0h92toGu434bZv6Dp+e0NzVGsK6qW3mY6kAqje8OBpmNeEb98r9tmAxsA4aLd3Drj3WqmvAro3Q7sg",
	"Y2/Oz4K/vC7+Onw+fUHOGcYvhy/IfxCzM5kUPWXduLHxds/CekQrjHaN5Hp5qIHbGlhiHjI59Wi06b3F",
	"7taUuFE1d7j6GUmEQXs5sCQpJ9wQky9SgVZCFsWOq50YpasFpa8k1q2RSKuUSFhZaFARlXAwuNMGnJVZ",
	"PtIFCITU3GYHyreJm7rTTGtW9JmDkwqOGopdvsD3xtvAnirCGTLCrphI2CKBP8pBrFvd9LfiyU4rMXcr",
	"nZC21d95vup2suxbFHZFjwEkFzF0dwpD3EhUa+xuy7CTPJaEJUulBcbpbgluUWaXBiNc4zBLmOhXXxfh",
	"tH41rBSYjvyD8eTZ9Pmhd0A3RJahRZ8G9P8fP/KnT3bIxe2adtbGgSUaGC82Z02Ymgl+37V9CqsuniwM",
	"IbPbuy2hP0nAdnuKw4cUyKTCGHQT5q5+o5Xnr5qQkus/4nlLYDUshcHqA8UOF16usBorYXUP/0FmUUt3",
	"BnaulH1NCZkVIdZxODZW/6vWemLWefzjW36zbykpUnbENfinGRm2CDlEy1/nZHpm+6TkaTXUyL6CfJST",
	"WdOyNR2t8Wqsv7nj94tYGFS6sNdbazNJGYc7uZjWbfYAJ3PZyvd32JnWt7o7eJrWq+Uapvv7mtV2kEjl",
	"8s/6RrKdpBuBvwMAAP//ptaGVi4XAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
