//nolint:all
//go:build go1.22

// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

type bearerAuthScopesCtxKey string
const (
	BearerAuthScopes bearerAuthScopesCtxKey = "bearerAuth.Scopes"
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	NEW        OrderStatus = "NEW"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
)

// Balance defines model for Balance.
type Balance struct {
	Current   float32 `json:"current"`
	Withdrawn float32 `json:"withdrawn"`
}

// Order defines model for Order.
type Order struct {
	Accrual    *float32    `json:"accrual,omitempty"`
	Number     string      `json:"number"`
	Status     OrderStatus `json:"status"`
	UploadedAt time.Time   `json:"uploaded_at"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       string    `json:"order"`
	ProcessedAt time.Time `json:"processed_at"`
	Sum         float32   `json:"sum"`
}

// PostUserBalanceWithdrawJSONBody defines parameters for PostUserBalanceWithdraw.
type PostUserBalanceWithdrawJSONBody struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// PostUserLoginJSONBody defines parameters for PostUserLogin.
type PostUserLoginJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// PostUserOrdersTextBody defines parameters for PostUserOrders.
type PostUserOrdersTextBody = string

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// PostUserBalanceWithdrawJSONRequestBody defines body for PostUserBalanceWithdraw for application/json ContentType.
type PostUserBalanceWithdrawJSONRequestBody PostUserBalanceWithdrawJSONBody

// PostUserLoginJSONRequestBody defines body for PostUserLogin for application/json ContentType.
type PostUserLoginJSONRequestBody PostUserLoginJSONBody

// PostUserOrdersTextRequestBody defines body for PostUserOrders for text/plain ContentType.
type PostUserOrdersTextRequestBody = PostUserOrdersTextBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current balance
	// (GET /user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Request withdrawal
	// (POST /user/balance/withdraw)
	PostUserBalanceWithdraw(w http.ResponseWriter, r *http.Request)
	// Authenticate an existing user
	// (POST /user/login)
	PostUserLogin(w http.ResponseWriter, r *http.Request)
	// Get list of submitted orders
	// (GET /user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Submit order number for processing
	// (POST /user/orders)
	PostUserOrders(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /user/register)
	PostUserRegister(w http.ResponseWriter, r *http.Request)
	// Get withdrawal history
	// (GET /user/withdrawals)
	GetUserWithdrawals(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserBalanceWithdraw operation middleware
func (siw *ServerInterfaceWrapper) PostUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserBalanceWithdraw(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUserLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserOrders operation middleware
func (siw *ServerInterfaceWrapper) PostUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserWithdrawals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/user/balance", wrapper.GetUserBalance)
	m.HandleFunc("POST "+options.BaseURL+"/user/balance/withdraw", wrapper.PostUserBalanceWithdraw)
	m.HandleFunc("POST "+options.BaseURL+"/user/login", wrapper.PostUserLogin)
	m.HandleFunc("GET "+options.BaseURL+"/user/orders", wrapper.GetUserOrders)
	m.HandleFunc("POST "+options.BaseURL+"/user/orders", wrapper.PostUserOrders)
	m.HandleFunc("POST "+options.BaseURL+"/user/register", wrapper.PostUserRegister)
	m.HandleFunc("GET "+options.BaseURL+"/user/withdrawals", wrapper.GetUserWithdrawals)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYX3PTuhP9Khr9eCNtHDch1AwPBfrj9k6n7dBy+wC9zMZe1wJHMtK6aS6T735HsuM/",
	"iUPTFhge7ptbS6vds+ccrfONh2qaKYmSDA++cRMmOAX3+ApSkCHax0yrDDUJdC/CXGuUZB/xFqZZijwY",
	"ed7uqMdjpadAPOBxqoB4j9M8Qx5wmU8nqPmix2eCkkjDTLa2D/279y56XOPXXGiMePChyqIZ8qrapCaf",
	"MSR74KmOUK8XAWGoc0hXi9imhPKpuZPv++Pn+/7ecOzVOwxpIa/tDkNAuTsWZT612Z8cXvIeP3t3+vrw",
	"/Pzo5C3v8aOTvw6Oj97U/z58Ywuqz6j/3XFEnqUKIow+Qbsx3Pd8b2fg7wy8i8EoGIyC4eiptxd4NtGq",
	"1ggId0hMcT30Cuxl8VVN7ZO7GnBZtqcAu90FtWxOI9+98dj3R8/8YVeZmVYhGvOdOr39i8GzwNsPRuN7",
	"1dnjxrbmvnRYgacoqIi1ku06NvZMDHMtaH5udVdgMkHQqA9ySuq//r/M4s/LCxvdreZB+bbOKiHK+MIG",
	"FjJWdj8JcvC8VVmCegqa2LvD8wt2cHbEe/wGtRFK8oAPdr1dz6KgMpSQCR7wPfevHs+AEpdZPzeo+5Pa",
	"F67RNSFCE2qRURHpHZIWeIOGUYKslClL1RxSmrNMCUmGlUEYyIiRIkhZpeLlklhpFwFySlCSCIEwYjaF",
	"Xe7S1GBPPIpsdUjvDeqlZdmemExJUyDqe57zLSWp9C3IstQGFEr2Pxsla+uzT080xjzg/+vX3tgvjbG/",
	"PMKB3C68fMUs9LZdQklm8tAyIM7TdM50iUxkcR56g3Xs3sv1au3iUVFBe/GRJNQSUmZQ36BmqLXSLVbx",
	"4EObTx+uFleOnFPQ8wK3qkOTqrJeu9P9ZWucfpXp7PnXHA0ZBlUfIWUqXm07qRnoyC4zGYYiFhgxJ5n1",
	"lp4p0+zp0kV4oTc09EpF8y3aWsrZEeEGUhHVflRmXb7JseFIbRtyzjAeDVzTa5480stW/WY8GjzKbzoM",
	"pli+LoV292pEWIktq5yrxeB783bo+V28NXkci1BY1sW5jIxb6ncudS0rOMLqK/hn6aFkRIPEDTmk6lrI",
	"zRo4aCBgGEiGt8KQkNcODRfS+Vmm1Y2IMGIunnPADIyZKR1tVsGxO/vR3O9ifFkW/6wSGSl0hl+kY9mK",
	"oUYa+Hv8u9yvoKm5X4dbv8Sr+M0N9VENFVRL75pL0hKgasOD1XBeEb559dh3PZ4gRKjd3nOknddKfRHY",
	"vjyaBRl7uX4S0cvb+T/7z8cv2BlQ8rL/gv1BlJ3KdN5R1sLJxtushaVES4w2SXK5PNQY2RogNQ9RTiWN",
	"Jr3X2N1QiZOq2WI6AJYKQ/aSgDQtFG6YySdTQdZCJvMNtz8zSpcLitGT2YGOxVpNmcSZhYYUU2mEhjZO",
	"CqdFlo8cFATh1Nw1MRQfIIuq06A1zLvmh+MSjgqKTaOD7w3XgT1RLAICBjcgUpik+FsNGctW1/0teWLt",
	"oNNOz91KZ6RN93djYXk7WfZN5nZFx4zILhJs7xSGOUmUa+xuy7DjPJEM0mulBSXTzRbcoMwmDya8pX6W",
	"guh2XxfhpPp6LB2YD/y94ejZ+Pm+t8dXTBbIos8D/vfHj9HTJxvs4m5PO23iAKlGiOarWhOmYoLfdW2f",
	"4KyNJ4QhZnZ7uyX8BxnY5pli/yEFglSUoK7DbDtvNPL8WQopuP49njcMVuO1MFT+prFhGi9WWI+VOLvH",
	"/MGO4obv9KyulP2SCcGaELQmHBur+2tsqZhlHv/NLb94bikoUnTENfiHDTIwCSOMr3/eJNOh7eOCp6Wo",
	"Cb6gfNQks6RlQx0NedWjv9nyJ45EGFJ6bq+3xmY2hQi3mmIat9kDJpnLRr6/Ypxp/Jy3xUzT+LRcwnT/",
	"uWa2HiRWufy9fkZZT7K0HhfVuBi5TnnA+5AJvrha/BsAAP//vpZM3nwXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
